source /etc/profile
# Add custom fpath with our functions
export FPATH=${HOME}/.zsh/functions:$FPATH

# Lines configured by zsh-newuser-install
HISTFILE=${HOME}/.histfile
HISTSIZE=2000
SAVEHIST=$HISTSIZE
setopt HIST_VERIFY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt hist_ignore_all_dups
setopt extendedglob

unsetopt beep

export PATH="/usr/local/opt/node@12/bin:$PATH:/usr/local/opt"

source /usr/local/opt/zinit/zinit.zsh
zinit load marlonrichert/zsh-autocomplete

# VIM key bindings
bindkey -v
# with some overrides
bindkey "^[[A" up-line-or-history
bindkey "^[[B" down-line-or-history

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"

zsh_cache=${HOME}/.zsh/cache
mkdir -p $zsh_cache

# Colorized prompt
MAGENTA="%{"$'\033[01;35m'"%}"
BLUE="%{"$'\033[01;34m'"%}"
BLACK="%{"$'\033[01;30m'"%}"
NORM="%{"$'\033[00m'"%}"

if [ -z "$INSIDE_EMACS" ]; then
  export PS1="${MAGENTA}%n@%m ${BLUE}%~ %#${NORM} "
fi

# local vars and alises
alias apgmy="apg -a 1 -m 12 -M NCLs -E 'O0I1l(){}[]\"|~\/:;^\`'"
alias apgmys='apg -a 0 -m 10 -M NCL -E O0I1l'

# Set up vim path and EDITOR
if [[ -d '/usr/local/Cellar/macvim' ]]; then
  vimpath=`ls /usr/local/Cellar/macvim/*/MacVim.app/Contents/MacOS/Vim | head -n1`
  alias vim=$vimpath
  export EDITOR=$vimpath
else
  export EDITOR=`which vim`
fi

setopt extended_glob
setopt autopushd
alias dv='dirs -v'
setopt auto_cd

if [ -z "$MC_TMPDIR" ] ; then # check for mc
  # key bindings
  bindkey "\e[3~"     delete-char         # [Del] deletes char under the cursor
  bindkey "^H"    history-beginning-search-backward
  # Ctrl-R reverse search
  bindkey '^R' history-incremental-search-backward

  # colored ls
  alias ls='ls --color=auto'

  for zshrc_include in ${HOME}/.zsh/includes/* ; do
          source $zshrc_include
  done
fi

# locales
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export RAILS_ENV="development"

export PKG_CONFIG_PATH=/opt/local/lib/pkgconfig
export JAVA_HOME="$(/usr/libexec/java_home)"

# disable auto-titles to stop zsh from messing up tmux's titles
export DISABLE_AUTO_TITLE="true"

if [ -f ${HOME}/.zshrc.local ]; then
  source "${HOME}/.zshrc.local"
fi

# Emacs
# alias e='TERM=xterm emacs -nw'
alias e='emacsclient -n'

# HOMEBREW
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# direnv hook
eval "$(direnv hook $0)"

# The next line updates PATH for the Google Cloud SDK.
source "${HOME}/google-cloud-sdk/path.zsh.inc"

# The next line enables shell command completion for gcloud.
source "${HOME}/google-cloud-sdk/completion.zsh.inc"

# enable rbenv
eval "$(rbenv init - --no-rehash)"

# zsh-autocomplete settings
zstyle ':autocomplete:*' min-delay 0.2
zstyle ':autocomplete:*' min-input 2
zstyle ':autocomplete:*' recent-dirs fasd
zstyle ':autocomplete:*' widget-style menu-complete
zstyle ':autocomplete:*' fzf-completion yes
zstyle ':autocomplete:*' list-lines 6

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
