source /etc/profile
# Add custom fpath with our functions
export FPATH=${HOME}/.zsh/functions:$FPATH

# Lines configured by zsh-newuser-install
HISTFILE=${HOME}/.histfile
HISTSIZE=2000
SAVEHIST=$HISTSIZE
setopt HIST_VERIFY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt hist_ignore_all_dups
setopt extendedglob
# setopt HIST_REDUCE_BLANKS
# setopt correctall # commands correction
 
unsetopt beep

# VIM key bindings
bindkey -v
# with some overrides
bindkey "^[[A" up-line-or-history
bindkey "^[[B" down-line-or-history

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename "$HOME/.zshrc"

# gentoo TAB completion
autoload -U compinit promptinit zrecompile
zsh_cache=${HOME}/.zsh/cache
mkdir -p $zsh_cache
compinit
promptinit #; prompt gentoo
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'

# SSH hosts tab completion
local _myhosts
_myhosts=( ${${${${(f)"$(<$HOME/.ssh/known_hosts)"}:#[0-9]*}%%\ *}%%,*} )
zstyle ':completion:*' hosts $_myhosts

# Colorized prompt
MAGENTA="%{"$'\033[01;35m'"%}"
BLUE="%{"$'\033[01;34m'"%}"
BLACK="%{"$'\033[01;30m'"%}"
NORM="%{"$'\033[00m'"%}"
export PS1="${MAGENTA}%n@%m ${BLUE}%~ %#${NORM} "

if [[ -f "$HOME/.amazon-keys" ]]; then
  source "$HOME/.amazon-keys";
fi

# local vars and alises
alias apgmy='apg -a 1 -m 12 -M NCL -E O0I1l'
alias apgmys='apg -a 0 -M NCL -E O0I1l'

# Set up vim path and EDITOR
if [[ -d '/usr/local/Cellar/macvim' ]]; then
  vimpath=`ls /usr/local/Cellar/macvim/*/MacVim.app/Contents/MacOS/Vim | head -n1`
  alias vim=$vimpath
  export EDITOR=$vimpath
else
  export EDITOR=`which vim`
fi

setopt extended_glob
setopt autopushd
alias dv='dirs -v'
setopt auto_cd

if [ -z "$MC_TMPDIR" ] ; then # check for mc
  # key bindings
  bindkey "\e[3~"     delete-char         # [Del] deletes char under the cursor
  bindkey "^H"    history-beginning-search-backward
  # Ctrl-R reverse search
  bindkey '^R' history-incremental-search-backward

  # colored ls
  alias ls='ls --color=auto'

  for zshrc_include in ${HOME}/.zsh/includes/S[0-9][0-9]*[^~] ; do
          source $zshrc_include
  done
fi

# locales
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export SYMFONY_ENV="dev"
export POKERRU_ENV="dev"
export SCUMMVM_PORT="128:0"
export RAILS_ENV="development"

export PKG_CONFIG_PATH=/opt/local/lib/pkgconfig
export JAVA_HOME="$(/usr/libexec/java_home)"
export DOCKER_HOST=tcp://

# disable auto-titles to stop zsh from messing up tmux's titles
export DISABLE_AUTO_TITLE="true"

if [ -f ${HOME}/.zshrc.local ]; then
  source "${HOME}/.zshrc.local"
fi

# if we're launching zsh in a dir with .rvmrc - then cd out of it, and then back
# in, to reinitialize rvm
if [ -f .rvmrc ] || [ -f .ruby-version ] || [ -f .ruby-gemset ]; then
  old_dir=`pwd`
  cd .. && cd $old_dir
fi
